version: 2

submodules:
  include:
    - docs/external/breathe
    - docs/external/sphinx-csharp

python:
   version: 3.7
   install:
      - requirements: docs/requirements.txt

formats:
  - pdf